### ISSUE TITLE
Connect function terminating the app

### ISSUE THREAD

**Issue by brascene** [frekisSDK/ios-sdk-sample#1]
Hi there, I've just downloaded the **FrekisSDKSample** and tried the app on my iPhoneSE, and what happens is that calling the _connect(lock_id)_ function is crashing the app.
Here's the screenshot about the error info:
<img width="1007" alt="Screen Shot 2020-08-17 at 1 46 27 PM" src="https://user-images.githubusercontent.com/20214107/90393176-8042df00-e090-11ea-85de-77953839d1b5.png">

I've entered the correct secret key and device ID, and I need help with this.
Thanks in advance!

**Comment by brascene** [comment]
Update: I've managed to make the connection work by unregistering the device from Frekis app (from Appstore), and now the connect function is passing but it's returning that asset connection is failed. Since I don't have any other info about why it's not connected, can you suggest anything to check if I'm doing or not?
Thanks!

**Comment by frekisSDK** [comment]
Hello @brascene ,

I need a few for info about this issue. Could just check if the lock is not connected with any other app or other device

Thanks!

**Comment by brascene** [comment]
Hi,

The situation is like this, my iPhone is not connected to any other devices via Bluetooth except with the lock device, I have Frekis app installed on my iPhone and everything works fine with it. Then I've installed this example app and tried the same thing but it's not working, specifically the connect function is failing to connect and I can't see any errors. 
I've also tried to remove Frekis app from my phone and again try with example app but still the same issue.

**Comment by frekisSDK** [comment]
Hi @brascene 

At the time of trial with example app, Frekis app is running in the background ?

Thanks

**Comment by frekisSDK** [comment]
After bit debugging.. We found out you were using wrong API key to connect your asset. Asset was registered on different frekis account and you were using different account. 

Account is basically linked with your api_secret key.

You can only access your owned or shared assets.

I'm closing this issue for now. Let us know if you have any more questions.

**Comment by brascene** [comment]
Yes, thank you for your assistance!
